import type { ChangePlan, EntityRecord } from '../domain';
import type { IndexSnapshot } from '../indexing';
import type { MarkdownChangePlanner, MarkdownPlanningPort } from './MarkdownChangePlanner';

export interface ForeshadowingPatch { truth_event_ids?: string[]; plant_before?: string[]; advance_when?: string[]; reveal_after?: string[]; status?: 'planned' | 'planted' | 'advanced' | 'revealed' | 'abandoned' }
const transitions: Record<string, string[]> = { planned: ['planted', 'abandoned'], planted: ['advanced', 'revealed', 'abandoned'], advanced: ['advanced', 'revealed', 'abandoned'], revealed: ['planted'], abandoned: ['planted'] };
const yaml = (value: unknown) => JSON.stringify(value);
function patchFrontmatter(content: string, patch: ForeshadowingPatch): string { const normalized = content.replace(/\r\n/g, '\n'); const end = normalized.startsWith('---\n') ? normalized.indexOf('\n---', 4) : -1; if (end < 0) throw new Error('INVALID_FORESHADOWING_FRONTMATTER'); const lines = normalized.slice(4, end).split('\n'); const pending = new Set(Object.keys(patch)); const output = lines.map(line => { const key = line.match(/^([\w-]+):/)?.[1]; if (!key || !(key in patch)) return line; pending.delete(key); return `${key}: ${yaml(patch[key as keyof ForeshadowingPatch])}`; }); for (const key of [...pending].sort()) output.push(`${key}: ${yaml(patch[key as keyof ForeshadowingPatch])}`); return `---\n${output.join('\n')}\n---${normalized.slice(end + 4)}`; }
export class ForeshadowingCommandService {
	constructor(private snapshotProvider: () => IndexSnapshot | undefined, private port: MarkdownPlanningPort, private planner: MarkdownChangePlanner) {}
	async planUpdate(key: string, patch: ForeshadowingPatch, requestedAt = new Date().toISOString()): Promise<ChangePlan> { const snapshot = this.snapshotProvider(); const record: EntityRecord | undefined = snapshot?.byKey.get(key) || snapshot?.idRegistry.resolve(key); if (!snapshot) throw new Error('INDEX_UNAVAILABLE'); if (record?.type !== 'foreshadowing' || record.data.legacyKind) throw new Error('FORESHADOWING_NOT_WRITABLE'); const status = typeof record.data.status === 'string' ? record.data.status : 'planned'; if (patch.status && !transitions[status]?.includes(patch.status)) throw new Error('FORESHADOWING_TRANSITION_NOT_ALLOWED'); const source = await this.port.read(record.source.path); if (!source) throw new Error('FORESHADOWING_SOURCE_NOT_FOUND'); return this.planner.plan({ type: 'update-entity-fields', actor: 'author', requestedAt, targetKeys: [record.id || record.key], payload: { mutations: [{ path: record.source.path, operation: 'modify', content: patchFrontmatter(source.content, patch) }] } }, snapshot.version); }
}
