import { describe, expect, it } from 'vitest';
import { ActionProjectionService } from '../../src/console/application';
import { record, snapshot } from './wave3-fixtures';
import { eventRecord } from './wave4-fixtures';
import { taskRecord } from './wave5-fixtures';
describe('ActionProjectionService', () => {
	it('groups now/upcoming/missed/later/needs_confirmation by cursor distance and priority', () => { const events = [eventRecord('EVT-0001'), eventRecord('EVT-0002', { prerequisiteEventIds: ['EVT-0001'] }), eventRecord('EVT-0003', { prerequisiteEventIds: ['EVT-0002'] })]; const tasks = [taskRecord('TSK-0001', { activation: { relation: 'at', anchorType: 'event', anchorId: 'EVT-0002' } }), taskRecord('TSK-0002', { activation: { relation: 'before', anchorType: 'event', anchorId: 'EVT-0003' } }), taskRecord('TSK-0003', { activation: { relation: 'at', anchorType: 'event', anchorId: 'EVT-0001' } }), taskRecord('TSK-0004', { activation: { relation: 'at', anchorType: 'event', anchorId: 'EVT-9999' } }), taskRecord('TSK-0005', { activation: { relation: 'at', anchorType: 'event', anchorId: 'EVT-0003' }, status: 'blocked' })]; const actions = new ActionProjectionService(snapshot(...events, ...tasks), { schemaVersion: 1, currentFocus: 'CH-0001', storylineCursors: { 主线: 'EVT-0002' } }, 2).project(); expect(Object.fromEntries(actions.map(item => [item.key, item.group]))).toEqual({ 'TSK-0001': 'now', 'TSK-0002': 'upcoming', 'TSK-0003': 'missed', 'TSK-0004': 'needs_confirmation', 'TSK-0005': 'now' }); });
	it('does not activate hidden/history/non-current-line merely because occurred and aggregates legacy tasks read-only', () => { const hidden = eventRecord('EVT-0001', { eventStatus: 'occurred', storyline: '历史线', timelineViews: { hiddenWorld: { visible: true }, characters: {}, organizations: {} } }); const modern = taskRecord('TSK-0001', { activation: { relation: 'after', anchorType: 'event', anchorId: 'EVT-0001' } }); const legacy = record('task', undefined, { title: '旧任务', legacyKind: 'timed-task', endDate: '2025-01-01', status: '进行中' }); const actions = new ActionProjectionService(snapshot(hidden, modern, legacy), { schemaVersion: 1, currentFocus: 'CH-0001', storylineCursors: { 主线: 'EVT-0009' } }).project(); expect(actions.find(item => item.key === 'TSK-0001')?.group).toBe('later'); expect(actions.find(item => item.source === 'legacy_timed_task')?.group).toBe('missed'); });
	it('handles between, milestone, resolved blockers, terminal tasks, and unconfigured cursors', () => { const event = eventRecord('EVT-0001', { eventStatus: 'occurred' }); const done = taskRecord('TSK-0009', { status: 'completed' }); const tasks = [taskRecord('TSK-0001', { activation: { relation: 'between', anchorType: 'event', startAnchorId: 'EVT-0001', endAnchorId: 'EVT-0002' } }), taskRecord('TSK-0002', { activation: { relation: 'blocked_by', anchorType: 'task', blockerIds: ['TSK-0009'] } }), taskRecord('TSK-0003', { activation: { relation: 'at', anchorType: 'milestone', anchorId: 'MLS-0001' } }), done]; const actions = new ActionProjectionService(snapshot(event, eventRecord('EVT-0002'), record('milestone', 'MLS-0001'), ...tasks), null).project(); expect(actions.find(item => item.key === 'TSK-0001')?.group).toBe('later'); expect(actions.find(item => item.key === 'TSK-0002')?.group).toBe('later'); expect(actions.find(item => item.key === 'TSK-0003')?.reason).toContain('里程碑'); expect(actions.some(item => item.key === 'TSK-0009')).toBe(false); });
});
