import { describe, expect, it } from 'vitest';
import { ForeshadowingPropertiesAdapter } from '../../src/console/adapters';
import { ForeshadowingActionRules } from '../../src/console/application';
import { ForeshadowingCommandService, MarkdownChangePlanner } from '../../src/console/persistence';
import { memoryPlanningPort, record, snapshot } from './wave3-fixtures';
import { eventRecord } from './wave4-fixtures';
describe('foreshadowing', () => {
	it('parses stable truth/plant/advance/reveal anchors without upgrading legacy data', () => { const parsed = new ForeshadowingPropertiesAdapter().parse({ path: '作品/FSH.md', basename: 'FSH', mtime: 1, contentHash: 'h', content: '# 伏笔', frontmatter: { type: 'foreshadowing', id: 'FSH-0001', truth_event_ids: ['EVT-0001'], plant_before: ['EVT-0002'], advance_when: ['EVT-0003'], reveal_after: ['EVT-0004'] } })[0]; expect(parsed?.data).toMatchObject({ truth_event_ids: ['EVT-0001'], plant_before: ['EVT-0002'], advance_when: ['EVT-0003'], reveal_after: ['EVT-0004'] }); });
	it('plans author-controlled status updates and derives approaching/passed reminders', async () => { const first = eventRecord('EVT-0001'); const second = eventRecord('EVT-0002', { prerequisiteEventIds: ['EVT-0001'] }); const third = eventRecord('EVT-0003', { prerequisiteEventIds: ['EVT-0002'] }); const fsh = record('foreshadowing', 'FSH-0001', { status: 'planned', plant_before: ['EVT-0002'] }); const port = memoryPlanningPort({ [fsh.source.path]: '---\ntype: foreshadowing\nid: FSH-0001\nstatus: planned\n---\n正文' }); const snap = snapshot(first, second, third, fsh); expect(new ForeshadowingActionRules(snap, { schemaVersion: 1, currentFocus: 'CH-0001', storylineCursors: { 主线: 'EVT-0001' } }).evaluate(fsh)[0]?.ruleId).toBe('PROG_FORESHADOWING_OVERDUE'); expect(new ForeshadowingActionRules(snap, { schemaVersion: 1, currentFocus: 'CH-0001', storylineCursors: { 主线: 'EVT-0003' } }).evaluate(fsh)[0]?.ruleId).toBe('PROG_FORESHADOWING_ANCHOR_PASSED'); const plan = await new ForeshadowingCommandService(() => snap, port, new MarkdownChangePlanner(port)).planUpdate('FSH-0001', { status: 'planted', reveal_after: ['EVT-0003'] }); expect(plan.files[0]?.content).toContain('reveal_after: ["EVT-0003"]'); });
	it('rejects legacy writes, forbidden transitions, missing sources, and invalid frontmatter', async () => { const modern = record('foreshadowing', 'FSH-0001', { status: 'planned' }); const legacy = record('foreshadowing', undefined, { legacyKind: 'foreshadowing' }); const missing = memoryPlanningPort(); const missingService = new ForeshadowingCommandService(() => snapshot(modern, legacy), missing, new MarkdownChangePlanner(missing)); await expect(missingService.planUpdate(legacy.key, { status: 'planted' })).rejects.toThrow('FORESHADOWING_NOT_WRITABLE'); await expect(missingService.planUpdate('FSH-0001', { status: 'revealed' })).rejects.toThrow('FORESHADOWING_TRANSITION_NOT_ALLOWED'); await expect(missingService.planUpdate('FSH-0001', { status: 'planted' })).rejects.toThrow('FORESHADOWING_SOURCE_NOT_FOUND'); const bad = memoryPlanningPort({ [modern.source.path]: 'bad' }); await expect(new ForeshadowingCommandService(() => snapshot(modern), bad, new MarkdownChangePlanner(bad)).planUpdate('FSH-0001', { status: 'planted' })).rejects.toThrow('INVALID_FORESHADOWING_FRONTMATTER'); });
	it('uses the anchor event storyline and never guesses from another line cursor', () => { const main = eventRecord('EVT-0001', { storyline: '主线' }); const side = eventRecord('EVT-0002', { storyline: '支线' }); const fsh = record('foreshadowing', 'FSH-0001', { status: 'planned', plant_before: ['EVT-0002'] }); const snap = snapshot(main, side, fsh); expect(new ForeshadowingActionRules(snap, { schemaVersion: 1, currentFocus: null, storylineCursors: { 主线: 'EVT-0001' } }).evaluate(fsh)).toEqual([]); expect(new ForeshadowingActionRules(snap, { schemaVersion: 1, currentFocus: null, storylineCursors: { 支线: 'EVT-0002' } }).evaluate(fsh)[0]?.evidence[0]?.value).toBe('EVT-0002'); });
});
