import { describe, expect, it } from 'vitest';
import { HEALTH_RULE_IDS, HealthRuleRegistry } from '../../src/console/application';
import { record, snapshot } from './wave3-fixtures';
import { eventRecord } from './wave4-fixtures';
import { taskRecord } from './wave5-fixtures';
describe('HealthRuleRegistry', () => {
	it('publishes every frozen stable rule id exactly once in the catalog', () => { expect(HEALTH_RULE_IDS).toHaveLength(34); expect(new Set(HEALTH_RULE_IDS).size).toBe(34); });
	it('emits evidence-backed structure, event, continuity, and progression findings without auto-fixing facts', () => { const current = eventRecord('EVT-0001', { eventStatus: 'occurring', prerequisiteEventIds: ['EVT-9999'], currentChapterIds: ['CH-9999'] }); const item = record('item', 'ITM-0001', { current_holder_ids: ['CHR-0001', 'CHR-0002'] }); const character = record('character', 'CHR-0001', { current_location_id: 'LOC-9999' }); const task = taskRecord('TSK-0001', { activation: { relation: 'at', anchorType: 'event', anchorId: 'EVT-8888' } }); const snap = snapshot(current, item, character, task); const results = new HealthRuleRegistry().evaluate(snap, { schemaVersion: 1, currentFocus: 'CH-0001', storylineCursors: { 主线: 'EVT-0001' } }); expect(results.map(item => item.ruleId)).toEqual(expect.arrayContaining(['EVENT_TIME_MISSING', 'EVENT_DEPENDENCY_MISSING', 'CONTINUITY_CHAPTER_EVENT_MAPPING_BROKEN', 'CONTINUITY_ITEM_MULTIPLE_HOLDERS', 'CONTINUITY_CHARACTER_LOCATION_CONFLICT', 'PROG_ACTIVATION_ANCHOR_INVALID'])); expect(results.every(item => !item.autoFixKind)).toBe(true); expect(results.every(item => item.evidence.length > 0)).toBe(true); });
	it('covers cross-scope, deprecated, time, prerequisite, milestone-cycle, ownership, hidden activation, and ignored-relevant evidence', () => { const old = eventRecord('EVT-0001', { eventStatus: 'planned', storyline: '旧线', storyTime: { display: '2', sortKey: '2', calendar: '历', precision: 'day' }, storyTimeEnd: { display: '1', sortKey: '1', calendar: '历', precision: 'day' }, timelineViews: { hiddenWorld: { visible: true }, characters: {}, organizations: {} } }); old.contextScope = 'history'; old.lifecycleStatus = 'deprecated'; const current = eventRecord('EVT-0002', { prerequisiteEventIds: ['EVT-0001'], currentChapterIds: ['CH-0001'] }); current.links.push({ type: 'ref', fromKey: current.key, toRef: 'EVT-0001', direction: 'outgoing', source: current.source }); const cycleA = eventRecord('EVT-0003', { prerequisiteEventIds: ['EVT-0004'] }); const cycleB = eventRecord('EVT-0004', { prerequisiteEventIds: ['EVT-0003'] }); const milestone = record('milestone', 'MLS-0001', { completion: { required_event_ids: ['EVT-0003'] } }); const item = record('item', 'ITM-0001', { holder_history: [{ holder: 'CHR-0001' }] }); const task = taskRecord('TSK-0001', { activation: { relation: 'at', anchorType: 'event', anchorId: 'EVT-0001' } }); const snap = snapshot(old, current, cycleA, cycleB, milestone, item, task, record('chapter', 'CH-0001')); const ignored = new Map([['SUG:PROG_TASK_ANCHOR_PASSED:TSK-0001:EVT-0001', { suggestionId: 'SUG:PROG_TASK_ANCHOR_PASSED:TSK-0001:EVT-0001', ruleId: 'PROG_TASK_ANCHOR_PASSED', targetKey: 'TSK-0001', decision: 'ignored_once' as const, decidedAt: '2026-01-01' }]]); const results = new HealthRuleRegistry().evaluate(snap, { schemaVersion: 1, currentFocus: 'CH-0001', storylineCursors: { 主线: 'EVT-0002', 旧线: 'EVT-0001' } }, ignored); expect(results.map(item => item.ruleId)).toEqual(expect.arrayContaining(['STRUCT_CANON_REFERENCES_DEPRECATED', 'STRUCT_CONTEXT_SCOPE_LEAK', 'EVENT_TIME_CONFLICT', 'EVENT_CROSSLINE_JOIN_UNMET', 'EVENT_DEPENDENCY_CYCLE', 'MILESTONE_DEPENDENCY_CYCLE', 'CONTINUITY_ITEM_OWNERSHIP_REVIEW', 'PROG_HIDDEN_HISTORY_TASK_ACTIVATED'])); });
});
