import { describe, expect, it } from 'vitest';
import { SuggestionCommandService, SuggestionService } from '../../src/console/application';
import { createSuggestionId } from '../../src/console/domain';
import { createDefaultConsoleProject } from '../../src/console/config';
import { CreativeTaskRepository, MarkdownChangePlanner, SuggestionDecisionRepository, parseSuggestionDecisions } from '../../src/console/persistence';
import { memoryPlanningPort, snapshot } from './wave3-fixtures';
import { taskData } from './wave5-fixtures';
describe('suggestions', () => {
	it('deduplicates deterministic identities and applies the latest terminal decision', () => { const diagnostic = { ruleId: 'PROG_TASK_ANCHOR_PASSED', severity: 'suggestion' as const, entityKey: 'TSK-0001', message: 'passed', evidence: [{ path: 'x.md', value: 'EVT-0001' }] }; const id = createSuggestionId({ ruleId: diagnostic.ruleId, targetKey: diagnostic.entityKey, anchorId: 'EVT-0001' }); expect(new SuggestionService().derive([diagnostic, diagnostic])).toHaveLength(1); expect(new SuggestionService().derive([diagnostic], new Map([[id, { suggestionId: id, ruleId: diagnostic.ruleId, targetKey: 'TSK-0001', decision: 'handled', decidedAt: '2026-01-01' }]]))).toHaveLength(0); });
	it('appends history and only conversion creates a TSK in the same confirmed plan', async () => { const project = createDefaultConsoleProject('作品'); const port = memoryPlanningPort(); const planner = new MarkdownChangePlanner(port); const decisions = new SuggestionDecisionRepository(project, port, planner); const tasks = new CreativeTaskRepository(() => snapshot(), project, port, planner); const commands = new SuggestionCommandService(decisions, tasks); const entry = { suggestionId: 'SUG:R:X:none', ruleId: 'R', targetKey: 'X', decision: 'converted_to_task' as const, decidedAt: '2026-01-01T00:00:00.000Z', resultingTaskId: 'TSK-0001' }; const plan = await commands.planConvert(entry, { id: 'TSK-0001', title: '正式任务', data: taskData() }, 'snapshot-v3'); expect(plan.command.type).toBe('convert-suggestion-to-task'); expect(plan.files.map(file => file.path)).toEqual(['作品/总控系统/创作任务/TSK-0001-正式任务.md', '作品/总控系统/建议决策.md']); expect(plan.requiresConfirmation).toBe(true); const log = plan.files[1]?.content || ''; expect(parseSuggestionDecisions(log)[0]?.resultingTaskId).toBe('TSK-0001'); });
	it('reads latest decisions, appends non-conversion choices, and rejects invalid conversions', async () => { const project = createDefaultConsoleProject('作品'); const path = '作品/总控系统/建议决策.md'; const old = { suggestionId: 'SUG:R:X:none', ruleId: 'R', targetKey: 'X', decision: 'ignored_once' as const, decidedAt: '2025-01-01' }; const latest = { ...old, decision: 'snoozed' as const, decidedAt: '2026-01-01' }; const port = memoryPlanningPort({ [path]: `---\ndecisions: ${JSON.stringify([old, latest])}\n---\n` }); const planner = new MarkdownChangePlanner(port); const repository = new SuggestionDecisionRepository(project, port, planner); expect((await repository.latest()).get(old.suggestionId)?.decision).toBe('snoozed'); expect((await repository.planAppend({ ...latest, decision: 'handled' }, 'v1')).files[0]?.operation).toBe('modify'); const commands = new SuggestionCommandService(repository, new CreativeTaskRepository(() => snapshot(), project, port, planner)); expect((await commands.planDecision({ ...latest, decision: 'not_applicable' }, 'v1')).command.type).toBe('append-suggestion-decision'); expect(() => commands.planDecision({ ...latest, decision: 'converted_to_task' }, 'v1')).toThrow('USE_PLAN_CONVERT'); await expect(repository.planAppend({ ...latest, decision: 'converted_to_task' }, 'v1')).rejects.toThrow('RESULTING_TASK_REQUIRED'); expect(parseSuggestionDecisions('decisions: bad')).toEqual([]); });
});
