import { ENTITY_ID_PREFIX, hasValidIdShape, type DiagnosticRef, type EntityRecord } from '../domain';
import type { IndexSnapshot } from '../indexing';
import type { ProjectState, SuggestionDecisionEntry } from '../persistence';
import { creativeTaskDataFromRecord, eventDataFromRecord } from '../persistence';
import { EventGraph } from './EventGraph';
import { ActionProjectionService } from './ActionProjectionService';
import { ForeshadowingActionRules } from './ForeshadowingActionRules';

export const STRUCTURE_RULE_IDS = ['STRUCT_ID_DUPLICATE', 'STRUCT_ID_MISSING', 'STRUCT_ID_TYPE_MISMATCH', 'STRUCT_ID_FORMAT_NONSTANDARD', 'STRUCT_WIKILINK_BROKEN', 'STRUCT_CORE_ORPHANED', 'STRUCT_DIRECTORY_STATUS_MISMATCH', 'STRUCT_CANON_REFERENCES_DEPRECATED', 'STRUCT_CONTEXT_SCOPE_LEAK', 'STRUCT_REVIEW_STALE', 'STRUCT_MANUSCRIPT_UNKNOWN_REFERENCE', 'STRUCT_FIELD_ALIAS_CONFLICT', 'STRUCT_ENUM_UNKNOWN'] as const;
export const CONTINUITY_RULE_IDS = ['EVENT_TIME_MISSING', 'EVENT_TIME_CONFLICT', 'EVENT_DEPENDENCY_MISSING', 'EVENT_DEPENDENCY_CYCLE', 'EVENT_CURRENT_PREREQUISITE_MISSING', 'EVENT_CHAPTER_PREREQUISITE_UNMET', 'EVENT_CROSSLINE_JOIN_UNMET', 'MILESTONE_EVENT_MISSING', 'MILESTONE_DEPENDENCY_CYCLE', 'CONTINUITY_CHARACTER_LOCATION_CONFLICT', 'CONTINUITY_CHARACTER_STATE_REVIEW', 'CONTINUITY_ITEM_MULTIPLE_HOLDERS', 'CONTINUITY_ITEM_OWNERSHIP_REVIEW', 'CONTINUITY_KNOWLEDGE_REVIEW', 'CONTINUITY_CHAPTER_EVENT_MAPPING_BROKEN'] as const;
export const PROGRESSION_RULE_IDS = ['PROG_FORESHADOWING_OVERDUE', 'PROG_FORESHADOWING_ANCHOR_PASSED', 'PROG_TASK_ANCHOR_PASSED', 'PROG_ACTIVATION_ANCHOR_INVALID', 'PROG_HIDDEN_HISTORY_TASK_ACTIVATED', 'PROG_SUGGESTION_IGNORED_RELEVANT'] as const;
export const HEALTH_RULE_IDS = [...STRUCTURE_RULE_IDS, ...CONTINUITY_RULE_IDS, ...PROGRESSION_RULE_IDS] as const;
const diagnostic = (record: EntityRecord, ruleId: typeof HEALTH_RULE_IDS[number], message: string, field?: string, value?: unknown): DiagnosticRef => ({ ruleId, severity: ruleId.startsWith('PROG_') ? 'suggestion' : 'warning', entityKey: record.id || record.key, message, evidence: [{ path: record.source.path, field, value }] });
const ids = (value: unknown): string[] => Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : [];

export class HealthRuleRegistry {
	evaluate(snapshot: IndexSnapshot, state: ProjectState | null = null, decisions: ReadonlyMap<string, SuggestionDecisionEntry> = new Map()): DiagnosticRef[] {
		const result = [...snapshot.diagnostics.filter(item => (HEALTH_RULE_IDS as readonly string[]).includes(item.ruleId))]; const graph = new EventGraph(snapshot);
		for (const cycle of graph.detectCycles()) for (const id of cycle.slice(0, -1)) { const record = snapshot.idRegistry.resolve(id); if (record) result.push(diagnostic(record, 'EVENT_DEPENDENCY_CYCLE', '事件依赖形成环', 'prerequisite_event_ids', cycle)); }
		for (const record of snapshot.records) {
			this.structureRules(record, snapshot, result);
			if (record.type === 'event') this.eventRules(record, snapshot, state, result);
			else if (record.type === 'milestone') { const required = ids((record.data.completion as Record<string, unknown> | undefined)?.required_event_ids || (record.data.completion as Record<string, unknown> | undefined)?.requiredEventIds); for (const id of required) if (!snapshot.idRegistry.resolve(id)) result.push(diagnostic(record, 'MILESTONE_EVENT_MISSING', '里程碑引用的事件不存在', 'completion', id)); const cycleIds = new Set(graph.detectCycles().flat()); if (required.some(id => cycleIds.has(id))) result.push(diagnostic(record, 'MILESTONE_DEPENDENCY_CYCLE', '里程碑依赖的事件存在环', 'completion', required)); }
			else if (record.type === 'character') { const location = record.data.current_location_id; if (typeof location === 'string' && !snapshot.idRegistry.resolve(location)) result.push(diagnostic(record, 'CONTINUITY_CHARACTER_LOCATION_CONFLICT', '人物当前位置不存在', 'current_location_id', location)); if (!record.data.story_status) result.push(diagnostic(record, 'CONTINUITY_CHARACTER_STATE_REVIEW', '人物故事状态需要复核', 'story_status')); }
			else if (record.type === 'item') { const holders = ids(record.data.current_holder_ids); if (holders.length > 1) result.push(diagnostic(record, 'CONTINUITY_ITEM_MULTIPLE_HOLDERS', '道具存在多个当前持有者', 'current_holder_ids', holders)); if (record.data.holder_history && !holders.length) result.push(diagnostic(record, 'CONTINUITY_ITEM_OWNERSHIP_REVIEW', '持有历史与当前持有状态需复核', 'holder_history')); }
			else if (record.type === 'task' && !record.data.legacyKind) { const task = creativeTaskDataFromRecord(record); const anchors = 'anchorId' in task.activation ? [task.activation.anchorId] : task.activation.relation === 'between' ? [task.activation.startAnchorId, task.activation.endAnchorId] : task.activation.blockerIds; if (anchors.some(id => !snapshot.idRegistry.resolve(id))) result.push(diagnostic(record, 'PROG_ACTIVATION_ANCHOR_INVALID', '任务激活锚点无效', 'activation', anchors)); }
			if (record.type === 'foreshadowing') result.push(...new ForeshadowingActionRules(snapshot, state).evaluate(record));
		}
		for (const action of new ActionProjectionService(snapshot, state).project()) if (action.source === 'creative_task') { const record = snapshot.idRegistry.resolve(action.key); if (!record) continue; if (action.group === 'missed') result.push(diagnostic(record, 'PROG_TASK_ANCHOR_PASSED', action.reason, 'activation', action.anchorIds)); if (action.group === 'now') { const hiddenAnchor = action.anchorIds.map(id => snapshot.idRegistry.resolve(id)).find(anchor => anchor?.type === 'event' && (anchor.contextScope === 'history' || (!eventDataFromRecord(anchor).timelineViews.reality?.visible && Boolean(eventDataFromRecord(anchor).timelineViews.hiddenWorld?.visible || eventDataFromRecord(anchor).timelineViews.cosmic?.visible)))); if (hiddenAnchor) result.push(diagnostic(record, 'PROG_HIDDEN_HISTORY_TASK_ACTIVATED', '隐藏或历史事件触发了当前任务，需要作者确认', 'activation', hiddenAnchor.id)); } }
		for (const [suggestionId, decision] of decisions) if (decision.decision === 'ignored_once' && result.some(item => suggestionId.includes(item.ruleId) && suggestionId.includes(item.entityKey))) { const target = snapshot.idRegistry.resolve(decision.targetKey); if (target) result.push(diagnostic(target, 'PROG_SUGGESTION_IGNORED_RELEVANT', '曾单次忽略的建议仍然相关', 'suggestion_id', suggestionId)); }
		return [...new Map(result.map(item => [`${item.ruleId}\0${item.entityKey}\0${JSON.stringify(item.evidence)}`, item])).values()];
	}
	private structureRules(record: EntityRecord, snapshot: IndexSnapshot, result: DiagnosticRef[]) {
		if (record.id && record.type !== 'unknown' && !hasValidIdShape(record.type, record.id)) { const belongsElsewhere = Object.entries(ENTITY_ID_PREFIX).some(([type, prefix]) => type !== record.type && record.id?.startsWith(`${prefix}-`)); result.push(diagnostic(record, belongsElsewhere ? 'STRUCT_ID_TYPE_MISMATCH' : 'STRUCT_ID_FORMAT_NONSTANDARD', belongsElsewhere ? 'ID 前缀与对象类型不匹配' : 'ID 格式非规范', 'id', record.id)); }
		for (const link of record.links) { const target = snapshot.idRegistry.resolve(link.toRef) || snapshot.byKey.get(link.toRef); if (!target) result.push(diagnostic(record, record.type === 'chapter' ? 'STRUCT_MANUSCRIPT_UNKNOWN_REFERENCE' : 'STRUCT_WIKILINK_BROKEN', '引用目标不存在', link.type, link.toRef)); else { if (record.canon === 'canon' && target.lifecycleStatus === 'deprecated') result.push(diagnostic(record, 'STRUCT_CANON_REFERENCES_DEPRECATED', '正式资料引用废弃对象', link.type, link.toRef)); if (record.contextScope === 'current' && ['history', 'test'].includes(target.contextScope)) result.push(diagnostic(record, 'STRUCT_CONTEXT_SCOPE_LEAK', '当前上下文引用历史或测试对象', link.type, link.toRef)); } }
		if (record.lifecycleStatus === 'archived' && !/(?:archive|归档)/i.test(record.source.path)) result.push(diagnostic(record, 'STRUCT_DIRECTORY_STATUS_MISMATCH', '归档状态与目录位置不一致', 'lifecycle_status'));
		if (record.reviewStatus === 'pending_review' && record.lastReviewed && Date.now() - Date.parse(record.lastReviewed) > 365 * 86_400_000) result.push(diagnostic(record, 'STRUCT_REVIEW_STALE', '资料复核已超过一年', 'last_reviewed', record.lastReviewed));
		if (['event', 'character', 'item', 'organization', 'location'].includes(record.type) && record.links.length === 0 && snapshot.relations.getIncoming(record.id || record.key).length === 0) result.push(diagnostic(record, 'STRUCT_CORE_ORPHANED', '核心对象没有可解析关系', undefined, record.id || record.key));
	}
	private eventRules(record: EntityRecord, snapshot: IndexSnapshot, state: ProjectState | null, result: DiagnosticRef[]) { const data = eventDataFromRecord(record); if (data.eventStatus === 'occurring' && !data.storyTime) result.push(diagnostic(record, 'EVENT_TIME_MISSING', '进行中事件缺少开始时间', 'story_time')); if (data.storyTime?.sortKey && data.storyTimeEnd?.sortKey && data.storyTime.calendar === data.storyTimeEnd.calendar && data.storyTime.sortKey > data.storyTimeEnd.sortKey) result.push(diagnostic(record, 'EVENT_TIME_CONFLICT', '事件结束时间早于开始时间', 'story_time_end', data.storyTimeEnd)); for (const id of data.prerequisiteEventIds) { const prerequisite = snapshot.idRegistry.resolve(id); if (!prerequisite) result.push(diagnostic(record, 'EVENT_DEPENDENCY_MISSING', '前置事件不存在', 'prerequisite_event_ids', id)); else if (prerequisite.type === 'event' && eventDataFromRecord(prerequisite).storyline !== data.storyline) result.push(diagnostic(record, 'EVENT_CROSSLINE_JOIN_UNMET', '跨线前置条件需明确汇合', 'prerequisite_event_ids', id)); else if (prerequisite.type === 'event' && eventDataFromRecord(prerequisite).eventStatus !== 'occurred') { if (state?.storylineCursors[data.storyline] === record.id) result.push(diagnostic(record, 'EVENT_CURRENT_PREREQUISITE_MISSING', '当前事件前置条件未满足', 'prerequisite_event_ids', id)); if (data.currentChapterIds.length) result.push(diagnostic(record, 'EVENT_CHAPTER_PREREQUISITE_UNMET', '章节承载事件的前置条件未满足', 'current_chapter_ids', data.currentChapterIds)); } } for (const chapterId of data.currentChapterIds) if (!snapshot.idRegistry.resolve(chapterId)) result.push(diagnostic(record, 'CONTINUITY_CHAPTER_EVENT_MAPPING_BROKEN', '事件映射章节不存在', 'current_chapter_ids', chapterId)); if (data.knowledgeState.reader !== data.readerState) result.push(diagnostic(record, 'CONTINUITY_KNOWLEDGE_REVIEW', '事件读者状态与知识投影需要复核', 'knowledge_state.reader', data.knowledgeState.reader)); }
}
